## MODELLING PHASE

In [1]:
#WE import the libraries
import pandas as pd
import numpy as np

In [2]:
#lets load our safaricom modelling datasts
scom=pd.read_csv(r"C:\Users\Win\NSE Project\Data\2013 to 2024 cosolidated_SAFARICOM_MODELLING_data.csv")
scom.head()

,DATE,Day Price,Change%,12m Low,12m High,Day Low,Day High,Previous,Volume_log,MA_5,...,MA_12,STD_12,MA_50,STD_50,MA_200,STD_200,MA_5_vs_MA_50,MA_12_vs_MA_200,HighVol_5_vs_50,Daily_Range
0,2013-01-03,5.15,0.0098,23.5,33.5,5.10,5.25,5.10,15.796857,5.125000,...,5.125000,0.035355,5.125000,0.035355,5.125000,0.035355,0,0,0,0.15
1,2013-01-04,5.25,0.0194,23.5,33.5,5.15,5.35,5.15,15.232795,5.166667,...,5.166667,0.076376,5.166667,0.076376,5.166667,0.076376,0,0,0,0.20
2,2013-01-07,5.35,0.0190,23.5,33.5,5.20,5.45,5.25,15.226156,5.212500,...,5.212500,0.110868,5.212500,0.110868,5.212500,0.110868,0,0,0,0.25
3,2013-01-08,5.60,0.0467,23.5,33.5,5.40,5.85,5.35,16.213306,5.290000,...,5.290000,0.198116,5.290000,0.198116,5.290000,0.198116,0,0,0,0.45
4,2013-01-09,5.80,0.0357,23.5,33.5,5.50,6.00,5.60,16.432366,5.430000,...,5.375000,0.273404,5.375000,0.273404,5.375000,0.273404,1,0,0,0.50

In [3]:
#we confirm that all our data is numerical
scom.info()

<class 'pandas.DataFrame'>
RangeIndex: 2979 entries, 0 to 2978
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             2979 non-null   str
 1   Day Price        2979 non-null   float64
 2   Change%          2979 non-null   float64
 3   12m Low          2979 non-null   float64
 4   12m High         2979 non-null   float64
 5   Day Low          2979 non-null   float64
 6   Day High         2979 non-null   float64
 7   Previous         2979 non-null   float64
 8   Volume_log       2979 non-null   float64
 9   MA_5             2979 non-null   float64
 10  STD_5            2979 non-null   float64
 11  MA_12            2979 non-null   float64
 12  STD_12           2979 non-null   float64
 13  MA_50            2979 non-null   float64
 14  STD_50           2979 non-null   float64
 15  MA_200           2979 non-null   float64
 16  STD_200          2979 non-null   float64
 17  MA_5_vs_MA_50    2979 non-null   int64
 18  MA_12_vs_MA_200  2979 non-null   int64
 19  HighVol_5_vs_50  2979 non-null   int64
 20  Daily_Range      2979 non-null   float64
dtypes: float64(17), int64(3), str(1)
memory usage: 488.9 KB

In [4]:
scom.columns

Index(['DATE', 'Day Price', 'Change%', '12m Low', '12m High', 'Day Low',
       'Day High', 'Previous', 'Volume_log', 'MA_5', 'STD_5', 'MA_12',
       'STD_12', 'MA_50', 'STD_50', 'MA_200', 'STD_200', 'MA_5_vs_MA_50',
       'MA_12_vs_MA_200', 'HighVol_5_vs_50', 'Daily_Range'],
      dtype='str')

In [5]:
# we engineer a new feature return
scom['return'] = np.log(scom['Day Price'] / scom['Day Price'].shift(1))

In [6]:
# we engineer the target 
scom['target'] = scom['return'].shift(-1)

In [7]:
# we create lagged return features
scom['lag1'] = scom['return'].shift(1)
scom['lag2'] = scom['return'].shift(2)
scom['lag3'] = scom['return'].shift(3)
scom['lag5'] = scom['return'].shift(5)

In [8]:
#we drp the null values that emanated from engineering
scom=scom.dropna().reset_index(drop=True)
scom.shape

(2972, 27)

In [9]:
scom.head(20)

,DATE,Day Price,Change%,12m Low,12m High,Day Low,Day High,Previous,Volume_log,MA_5,...,MA_5_vs_MA_50,MA_12_vs_MA_200,HighVol_5_vs_50,Daily_Range,return,target,lag1,lag2,lag3,lag5
0,2013-01-11,5.60,0.0000,23.5,33.5,5.60,5.70,5.60,15.306480,5.59,...,1,0,0,0.10,0.000000,0.000000,-0.035091,0.035091,0.045670,0.019231
1,2013-01-14,5.60,0.0000,23.5,33.5,5.60,5.70,5.60,16.209489,5.64,...,1,0,0,0.10,0.000000,0.008889,0.000000,-0.035091,0.035091,0.018868
2,2013-01-15,5.65,0.0089,23.5,33.5,5.55,5.80,5.60,16.274099,5.65,...,1,0,0,0.25,0.008889,0.017544,0.000000,0.000000,-0.035091,0.045670
3,2013-01-16,5.75,0.0177,23.5,33.5,5.65,5.85,5.65,16.027328,5.64,...,1,0,0,0.20,0.017544,0.000000,0.008889,0.000000,0.000000,0.035091
4,2013-01-17,5.75,0.0000,23.5,33.5,5.70,5.80,5.75,16.582616,5.67,...,1,0,0,0.10,0.000000,0.000000,0.017544,0.008889,0.000000,-0.035091
5,2013-01-18,5.75,0.0000,23.5,33.5,5.75,5.80,5.75,16.403184,5.70,...,1,1,0,0.05,0.000000,0.000000,0.000000,0.017544,0.008889,0.000000
6,2013-01-21,5.75,0.0000,23.5,33.5,5.50,5.80,5.75,17.600250,5.73,...,1,1,0,0.30,0.000000,-0.017544,0.000000,0.000000,0.017544,0.000000
7,2013-01-22,5.65,0.0174,23.5,33.5,5.55,5.75,5.75,16.275441,5.73,...,1,1,0,0.20,-0.017544,-0.008889,0.000000,0.000000,0.000000,0.008889
8,2013-01-23,5.60,0.0088,23.5,33.5,5.50,5.75,5.65,16.552718,5.70,...,1,1,0,0.25,-0.008889,0.000000,-0.017544,0.000000,0.000000,0.017544
9,2013-01-24,5.60,0.0000,23.5,33.5,5.50,5.70,5.60,16.186651,5.67,...,1,1,0,0.20,0.000000,-0.008969,-0.008889,-0.017544,0.000000,0.000000
10,2013-01-25,5.55,0.0089,23.5,33.5,5.35,5.65,5.60,15.995917,5.63,...,1,1,0,0.30,-0.008969,-0.027399,0.000000,-0.008889,-0.017544,0.000000
11,2013-01-28,5.40,0.0270,23.5,33.5,5.25,5.60,5.55,17.046844,5.56,...,1,1,0,0.35,-0.027399,-0.018692,-0.008969,0.000000,-0.008889,0.000000
12,2013-01-29,5.30,0.0185,23.5,33.5,5.20,5.40,5.40,16.170385,5.49,...,0,1,0,0.20,-0.018692,0.000000,-0.027399,-0.008969,0.000000,-0.017544
13,2013-01-30,5.30,0.0000,23.5,33.5,5.25,5.50,5.30,16.728432,5.43,...,0,1,0,0.25,0.000000,0.027909,-0.018692,-0.027399,-0.008969,-0.008889
14,2013-01-31,5.45,0.0283,23.5,33.5,5.30,5.50,5.30,15.115566,5.40,...,0,1,0,0.20,0.027909,0.009132,0.000000,-0.018692,-0.027399,0.000000
15,2013-02-01,5.50,0.0092,23.5,33.5,5.40,5.55,5.45,18.523532,5.39,...,0,1,0,0.15,0.009132,-0.009132,0.027909,0.000000,-0.018692,-0.008969
16,2013-02-04,5.45,0.0091,23.5,33.5,5.35,5.55,5.50,14.870485,5.40,...,0,1,0,0.20,-0.009132,-0.009217,0.009132,0.027909,0.000000,-0.027399
17,2013-02-05,5.40,0.0092,23.5,33.5,5.35,5.60,5.45,17.150501,5.42,...,0,0,0,0.25,-0.009217,0.000000,-0.009132,0.009132,0.027909,-0.018692
18,2013-02-06,5.40,0.0000,23.5,33.5,5.40,5.50,5.40,15.054841,5.44,...,0,0,0,0.10,0.000000,0.000000,-0.009217,-0.009132,0.009132,0.000000
19,2013-02-07,5.40,0.0000,23.5,33.5,5.40,5.50,5.40,17.406444,5.43,...,0,0,0,0.10,0.000000,0.027399,0.000000,-0.009217,-0.009132,0.027909

In [10]:
# we now define the features and the target
# we leave the return feature out so that the model doesnt see the future- preventing data leakage
feature_cols = ['Change%', 'Volume_log',
                'MA_5', 'MA_12', 'MA_50', 'MA_200',
                'STD_5', 'STD_12', 'STD_50', 'STD_200',
                'MA_5_vs_MA_50', 'MA_12_vs_MA_200', 'HighVol_5_vs_50',
                'Daily_Range',
                'lag1', 'lag2', 'lag3', 'lag5']

X = scom[feature_cols]
y = scom['target']

In [11]:
#we see the shape oof our features
X.shape

(2972, 18)

In [12]:
X.head()

,Change%,Volume_log,MA_5,MA_12,MA_50,MA_200,STD_5,STD_12,STD_50,STD_200,MA_5_vs_MA_50,MA_12_vs_MA_200,HighVol_5_vs_50,Daily_Range,lag1,lag2,lag3,lag5
0,0.0000,15.306480,5.59,5.431250,5.431250,5.431250,0.159687,0.253458,0.253458,0.253458,1,0,0,0.10,-0.035091,0.035091,0.045670,0.019231
1,0.0000,16.209489,5.64,5.450000,5.450000,5.450000,0.089443,0.243670,0.243670,0.243670,1,0,0,0.10,0.000000,-0.035091,0.035091,0.018868
2,0.0089,16.274099,5.65,5.470000,5.470000,5.470000,0.086603,0.238281,0.238281,0.238281,1,0,0,0.25,0.000000,0.000000,-0.035091,0.045670
3,0.0177,16.027328,5.64,5.495455,5.495455,5.495455,0.065192,0.241303,0.241303,0.241303,1,0,0,0.20,0.008889,0.000000,0.000000,0.035091
4,0.0000,16.582616,5.67,5.516667,5.516667,5.516667,0.075829,0.241523,0.241523,0.241523,1,0,0,0.10,0.017544,0.008889,0.000000,-0.035091

In [13]:
#we see the shape of our target variable
y.shape

(2972,)

In [14]:
y.head()

0    0.000000
1    0.008889
2    0.017544
3    0.000000
4    0.000000
Name: target, dtype: float64

## TRAIN_TEST SPLIT

In [15]:
# WE split data in terms of time
#2013-2021 =train
#2022-2023= validate
#2024=test
train = scom[scom['DATE'] < '2022-01-01']
val   = scom[(scom['DATE'] >= '2022-01-01') & (scom['DATE'] < '2024-01-01')]
test  = scom[scom['DATE'] >= '2024-01-01']

# Features and target split
X_train = train[feature_cols]
y_train = train['target']

X_val   = val[feature_cols]
y_val   = val['target']

X_test  = test[feature_cols]
y_test  = test['target']

In [16]:
X_train.head()

,Change%,Volume_log,MA_5,MA_12,MA_50,MA_200,STD_5,STD_12,STD_50,STD_200,MA_5_vs_MA_50,MA_12_vs_MA_200,HighVol_5_vs_50,Daily_Range,lag1,lag2,lag3,lag5
0,0.0000,15.306480,5.59,5.431250,5.431250,5.431250,0.159687,0.253458,0.253458,0.253458,1,0,0,0.10,-0.035091,0.035091,0.045670,0.019231
1,0.0000,16.209489,5.64,5.450000,5.450000,5.450000,0.089443,0.243670,0.243670,0.243670,1,0,0,0.10,0.000000,-0.035091,0.035091,0.018868
2,0.0089,16.274099,5.65,5.470000,5.470000,5.470000,0.086603,0.238281,0.238281,0.238281,1,0,0,0.25,0.000000,0.000000,-0.035091,0.045670
3,0.0177,16.027328,5.64,5.495455,5.495455,5.495455,0.065192,0.241303,0.241303,0.241303,1,0,0,0.20,0.008889,0.000000,0.000000,0.035091
4,0.0000,16.582616,5.67,5.516667,5.516667,5.516667,0.075829,0.241523,0.241523,0.241523,1,0,0,0.10,0.017544,0.008889,0.000000,-0.035091

In [17]:
X_train.tail()

,Change%,Volume_log,MA_5,MA_12,MA_50,MA_200,STD_5,STD_12,STD_50,STD_200,MA_5_vs_MA_50,MA_12_vs_MA_200,HighVol_5_vs_50,Daily_Range,lag1,lag2,lag3,lag5
2230,0.0013,15.260593,38.93,38.095833,39.634,40.62775,0.987801,1.019683,2.082886,2.139352,0,0,0,0.55,0.033082,0.015646,0.001315,0.005284
2231,0.0163,13.862204,39.20,38.325000,39.572,40.63675,0.844097,0.960232,2.043111,2.130105,0,0,0,2.10,0.001251,0.033082,0.015646,0.001317
2232,0.0152,12.709272,39.34,38.475000,39.485,40.64275,0.638749,0.861421,1.981502,2.123045,0,0,0,1.50,-0.016383,0.001251,0.033082,0.001315
2233,0.0284,14.117466,39.14,38.462500,39.380,40.64550,0.976217,0.873115,1.935411,2.118785,0,0,0,1.20,-0.015365,-0.016383,0.001251,0.015646
2234,0.0080,15.732124,38.74,38.479167,39.296,40.64850,0.971082,0.860089,1.903617,2.114516,0,0,0,0.85,-0.028798,-0.015365,-0.016383,0.033082

## MODELLING

### 1. NAIVE PREDICTOR
- this acts as the base, that is, the upcoming models should outperform these metrics

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Naive prediction: tomorrow = yesterday
y_pred_naive = X_val['lag1']  # lag1 = yesterday's return

mae = mean_absolute_error(y_val, y_pred_naive)
rmse = np.sqrt(mean_squared_error(y_val, y_pred_naive))  # compute RMSE manually
r2 = r2_score(y_val, y_pred_naive)

print("Naive Predictor Evaluation:")
print(f"MAE: {mae:.6f}, RMSE: {rmse:.6f}, R²: {r2:.4f}")

Naive Predictor Evaluation:
MAE: 0.021015, RMSE: 0.031064, R²: -0.9456

### Interpretation

- MAE ≈ 0.021
On average, the naive predictor is off by ~2.1% in daily returns.

- RMSE ≈ 0.031
Standard deviation of the errors ≈ 3.1%, slightly higher than MAE because RMSE penalizes large mistakes more.

- R² ≈ -0.946
Negative R² → the naive predictor is worse than simply predicting the mean of the target.
Not surprising: stocks are noisy, and yesterday’s return is often a poor predictor of tomorrow’s return.

### 2. LINEAR REGRESSION

In [19]:
# WE import the libraries
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [20]:
# we initialize the model
lr=LinearRegression()

In [21]:
#we train our model
lr.fit(X_train,y_train)

LinearRegression()

In [22]:
# we predict our target
y_pred_lr=lr.predict(X_val)

In [23]:
# we now evaluate our model
mae=mean_absolute_error(y_val,y_pred_lr)
rmse=np.sqrt(mean_squared_error(y_val,y_pred_lr))
r2=r2_score(y_val,y_pred_lr)

print("Linear Regression Evaluation")
print(f"RMSE={rmse},MAE={mae},r^2={r2}")

Linear Regression Evaluation
RMSE=0.0236099183713788,MAE=0.016686805130855954,r^2=-0.12396016342590932

### 3. RANDOM FOREST REGRESSION

In [24]:
from sklearn.ensemble import RandomForestRegressor

# Initializing model
rf = RandomForestRegressor(
    n_estimators=200,   # number of trees
    max_depth=8,        # limit depth to prevent overfitting
    random_state=42
)

In [25]:
# Training
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=8, n_estimators=200, random_state=42)

In [26]:
# Prediction
y_pred_rf = rf.predict(X_val)

In [27]:
# Evaluation
mae = mean_absolute_error(y_val, y_pred_rf)
rmse = np.sqrt(mean_squared_error(y_val, y_pred_rf))
r2 = r2_score(y_val, y_pred_rf)

print("Random Forest Evaluation:")
print(f"MAE: {mae:.6f}, RMSE: {rmse:.6f}, R²: {r2:.4f}")

Random Forest Evaluation:
MAE: 0.016345, RMSE: 0.023259, R²: -0.0908

### 4. XGBOOST

In [28]:
import xgboost as xgb

# Initializing model
xgbr = xgb.XGBRegressor(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    objective='reg:squarederror',
    random_state=42
)

In [29]:
# Training
xgbr.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [30]:
# Prediction
y_pred_xgb = xgbr.predict(X_val)

In [31]:
# Evaluate
mae = mean_absolute_error(y_val, y_pred_xgb)
rmse = np.sqrt(mean_squared_error(y_val, y_pred_xgb))
r2 = r2_score(y_val, y_pred_xgb)

print("XGBoost Evaluation:")
print(f"MAE: {mae:.6f}, RMSE: {rmse:.6f}, R²: {r2:.4f}")

XGBoost Evaluation:
MAE: 0.018237, RMSE: 0.025086, R²: -0.2689

## HYPERPARAMETER TUNING

#### 1.  Random search

In [32]:
from sklearn.model_selection import RandomizedSearchCV
# Parameter ranges
param_dist = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [5, 8, 12, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt']
}

In [33]:
rf = RandomForestRegressor(random_state=42)
random_search_rf = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=20,          # number of random combinations
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    random_state=42
)

In [34]:
random_search_rf.fit(X_train, y_train)
print("Random Search Best RF params:", random_search_rf.best_params_)
best_rf = random_search_rf.best_estimator_

C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
33 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Win\miniconda3\envs\nse_env\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [-0.01367805         nan -0.01669448 -0.0138973  -0.01637765         nan
 -0.01358654         nan         nan -0.01385466         nan         nan
 -0.01594494 -0.01165781 -0.01252445         nan         nan         nan
         nan         nan]
  warnings.warn(

Random Search Best RF params: {'n_estimators': 400, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'max_depth': None}

In [ ]:
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV

param_dist_xgb = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0]
}

xgbr = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

random_search_xgb = RandomizedSearchCV(
    estimator=xgbr,
    param_distributions=param_dist_xgb,
    n_iter=20,
    scoring='neg_mean_absolute_error',
    cv=3,
    n_jobs=-1,
    random_state=42
)

random_search_xgb.fit(X_train, y_train)
print("Random Search Best XGB params:", random_search_xgb.best_params_)
best_xgb = random_search_xgb.best_estimator_

In [ ]:
### we now do grid search