In [46]:
import pandas as pd
import glob
import os

In [47]:
# Path to our CSVs
csv_folder = r"C:\Users\Win\NSE Project\Data" # adjust if different
all_files = glob.glob(os.path.join(csv_folder, "NSE_data_all_stocks_*.csv"))

In [48]:
# Check columns in the first file
df = pd.read_csv(all_files[1])
print(df.columns)

Index(['DATE', 'CODE', 'NAME', '12m Low', '12m High', 'Day Low', 'Day High',
       'Day Price', 'Previous', 'Change', 'Change%', 'Volume', 'Adjust'],
      dtype='str')

In [43]:

df_list = []
for file in all_files:
    df = pd.read_csv(file)
    df.columns = df.columns.str.strip()  # remove any extra spaces
    
    # Convert DATE with explicit format
    df['DATE'] = pd.to_datetime(df['DATE'], format='%d-%b-%y', errors='coerce')
    
    df_list.append(df)

# Merge all CSVs into a single DataFrame
nse_data = pd.concat(df_list, ignore_index=True)

In [49]:
nse_data.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
0,2013-01-02,EGAD,Eaagads Ltd,8.2,14,25,25,25,25,-,-,-,-,NaN,NaN,NaN
1,2013-01-02,KUKZ,Kakuzi Plc,300,423.5,67.5,67.5,67.5,72,-4.5,6.25%,300,-,NaN,NaN,NaN
2,2013-01-02,KAPC,Kapchorua Tea Kenya Plc,59,95,118,118,118,118,-,-,-,59,NaN,NaN,NaN
3,2013-01-02,LIMT,Limuru Tea Plc,385,475,430,430,430,430,-,-,-,215,NaN,NaN,NaN
4,2013-01-02,SASN,Sasini Plc,14.8,19.6,11.7,12.05,11.9,11.7,0.2,1.71%,"14,500",-,NaN,NaN,NaN

In [50]:
nse_data.tail()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
204382,2024-12-31,NaN,NaN,2364.29,"3,457.87","3,402.80","3,402.80","3,402.80","3,380.24",22.56,0.67%,-,NaN,^N25I,NSE 25-Share Index,-
204383,2024-12-31,NaN,NaN,90.1,125.34,123.48,123.48,123.48,123.12,0.36,0.29%,-,NaN,^NASI,NSE All-Share Index,-
204384,2024-12-31,NaN,NaN,986.46,"1,108.71","1,107.41","1,107.41","1,107.41","1,093.87",13.54,1.24%,-,NaN,^NBDI,NSE Bonds Index,-
204385,2024-12-31,NaN,NaN,1535.23,"2,547.58","2,519.80","2,519.80","2,519.80","2,495.28",24.52,0.98%,-,NaN,^ZKEQTK,Zamara Kenya Equity Index (KES),-
204386,2024-12-31,NaN,NaN,818.46,"1,697.07","1,677.27","1,677.27","1,677.27","1,662.24",15.03,0.90%,-,NaN,^ZKEQTU,Zamara Kenya Equity Index (USD),-

In [52]:
nse_data.shape

(204387, 16)

In [62]:
nse_data["CODE"].unique()

<StringArray>
[   'EGAD',    'KUKZ',    'KAPC',    'LIMT',    'SASN',     'WTK',    'CGEN',
    'ABSA',    'COOP',     'DTK',    'EQTY',    'HFCK',     'KCB',     'NBK',
    'NCBA',    'SBIC',    'SCBK',    'EVRD',    'XPRS',      'KQ',     'LKL',
     'NMG',    'SMER',     'SGL',    'TPSE',    'UCHM',    'SCAN',     'ARM',
    'BAMB',    'CRWN',    'CABL',    'PORT',    'KENO',    'KEGN', 'KPLC-P4',
 'KPLC-P7',    'KPLC',    'TOTL',    'BRIT',     'CIC',     'JUB',    'KNRE',
    'LBTY',    'SLAM',    'CTUM',     'OCH',     'TCL',     'BOC',     'BAT',
    'CARB',    'EABL',    'ORCH',     'MSC',    'UNGA',    'SCOM',  '^FNK15',
  '^FNK25',   '^N20I',   '^NASI',     'IMH',    'HAFR',    'UMME',     'NSE',
    'FTGH',    'KURV',       nan,   '^N25I',    'FAHR',     'NBV',    'DCON',
     'GLD', '^ZKEQTK', '^ZKEQTU',     'BKG']
Length: 74, dtype: str

In [64]:
# now we filter our SCOM and KCB CODE (tickers)
#for safaricom
scom=nse_data[nse_data["CODE"]== "SCOM"].sort_values("DATE")
kcb=nse_data[nse_data["CODE"]=="KCB"].sort_values("DATE")

In [65]:
scom.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
54,2013-01-02,SCOM,Safaricom Plc,23.5,33.5,5,5.15,5.1,5,0.1,2.00%,"3,320,600",-,NaN,NaN,NaN
113,2013-01-03,SCOM,Safaricom Plc,23.5,33.5,5.1,5.25,5.15,5.1,0.05,0.98%,"7,252,500",-,NaN,NaN,NaN
172,2013-01-04,SCOM,Safaricom Plc,23.5,33.5,5.15,5.35,5.25,5.15,0.1,1.94%,"4,125,900",-,NaN,NaN,NaN
231,2013-01-07,SCOM,Safaricom Plc,23.5,33.5,5.2,5.45,5.35,5.25,0.1,1.90%,"4,098,600",-,NaN,NaN,NaN
290,2013-01-08,SCOM,Safaricom Plc,23.5,33.5,5.4,5.85,5.6,5.35,0.25,4.67%,"10,998,900",-,NaN,NaN,NaN

In [66]:
kcb.head()

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
12,2013-01-02,KCB,KCB Group Plc,33.75,55.5,30,30.5,30.25,29.75,0.5,1.68%,"144,500",-,NaN,NaN,NaN
71,2013-01-03,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,30.25,0.75,2.48%,"790,400",-,NaN,NaN,NaN
130,2013-01-04,KCB,KCB Group Plc,33.75,55.5,31,31.5,31,31,-,-,"5,264,700",-,NaN,NaN,NaN
189,2013-01-07,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,31,-,-,"2,037,700",-,NaN,NaN,NaN
248,2013-01-08,KCB,KCB Group Plc,33.75,55.5,30.25,31.25,31,31,-,-,"637,600",-,NaN,NaN,NaN

In [67]:
#we reset the indices
scom.reset_index(drop=True,inplace=True)
kcb.reset_index(drop=True,inplace=True)

In [68]:
scom.head(2)

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
0,2013-01-02,SCOM,Safaricom Plc,23.5,33.5,5,5.15,5.1,5,0.1,2.00%,"3,320,600",-,NaN,NaN,NaN
1,2013-01-03,SCOM,Safaricom Plc,23.5,33.5,5.1,5.25,5.15,5.1,0.05,0.98%,"7,252,500",-,NaN,NaN,NaN

In [69]:
kcb.head(2)

,DATE,CODE,NAME,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjust,Code,Name,Adjusted Price
0,2013-01-02,KCB,KCB Group Plc,33.75,55.5,30,30.5,30.25,29.75,0.5,1.68%,"144,500",-,NaN,NaN,NaN
1,2013-01-03,KCB,KCB Group Plc,33.75,55.5,30.25,31.5,31,30.25,0.75,2.48%,"790,400",-,NaN,NaN,NaN

In [70]:
len(scom)

2243

In [71]:
len(kcb)

2243

In [79]:
print(f"Safaricom data shape is: {scom.shape}")
print(f"KCB shape is: {kcb.shape}")

Safaricom data shape is: (2243, 16)
KCB shape is: (2243, 16)