## Phase 1: Data Collection & Infrastructure

The first step in building a predictive dashboard is acquiring and organizing reliable data. For this project, we focus on **Nairobi Securities Exchange (NSE) stock data**, providing a real-world context relevant to local financial markets.

We source historical stock prices from a **comprehensive dataset (2007–2024) of all NSE-listed companies**, available via Mendeley Data. Selected tickers include **Safaricom (SCOM)** and **KCB (KCB)**, two of the most actively traded stocks in Kenya.

The goal of this phase is to create a **clean, structured dataset** suitable for exploratory data analysis, feature engineering, and predictive modeling. Key considerations include:

- **Completeness:** Ensuring all trading days are represented.  
- **Accuracy:** Verifying that prices are correctly recorded for each day.  
- **Format:** Organizing data in a tabular structure with timestamps as the index for easy time series analysis.

By establishing a solid data foundation from this dataset, we ensure that subsequent analysis and modeling are **reliable, reproducible, and meaningful** for both visualization and forecasting.

In [16]:
# lets import our libraries
import pandas as pd

In [17]:
df = pd.read_csv(r"C:\Users\Win\NSE Project\NSE_data_all_stocks_2024.csv")

In [22]:
#lets convert Date column to datetime and parse the dates safely
df['Date'] = pd.to_datetime(df['Date'], format="%Y-%m-%d", errors='coerce')

In [21]:
df.head()

,Date,Code,Name,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjusted Price
0,2024-01-02,EGAD,Eaagads Ltd,10.35,14.5,12.8,12.8,12.8,13.95,-1.15,-8.24%,100,-
1,2024-01-02,KUKZ,Kakuzi Plc,342,440,385,385,385,385,-,-,-,-
2,2024-01-02,KAPC,Kapchorua Tea Kenya Plc,207,280,215,215,215,215,-,-,-,-
3,2024-01-02,LIMT,Limuru Tea Plc,365,380,380,380,380,380,-,-,-,-
4,2024-01-02,SASN,Sasini Plc,15.1,22,20,20,20,20,-,-,"3,300.00",-

In [25]:
#lets see how many unique tickers we have
df["Code"].unique()

<StringArray>
[   'EGAD',    'KUKZ',    'KAPC',    'LIMT',    'SASN',     'WTK',    'CGEN',
    'ABSA',     'BKG',    'COOP',     'DTK',    'EQTY',    'HFCK',     'IMH',
     'KCB',     'NBK',    'NCBA',    'SBIC',    'SCBK',    'DCON',    'EVRD',
    'XPRS',     'HBE',      'KQ',     'LKL',     'NBV',     'NMG',    'SMER',
     'SGL',    'TPSE',    'UCHM',    'SCAN',     'ARM',    'BAMB',    'CRWN',
    'CABL',    'PORT',    'KEGN', 'KPLC-P4', 'KPLC-P7',    'KPLC',    'TOTL',
    'UMME',    'BRIT',     'CIC',     'JUB',    'KNRE',    'LBTY',    'SLAM',
    'CTUM',    'HAFR',    'KURV',     'OCH',     'TCL',     'NSE',     'BOC',
     'BAT',    'CARB',    'EABL',    'FTGH',    'ORCH',     'MSC',    'UNGA',
    'SCOM',    'LAPR',     'GLD',   '^N10I',   '^N20I',   '^N25I',   '^NASI',
 '^ZKEQTK', '^ZKEQTU',   '^NBDI',  'HFCK-R']
Length: 74, dtype: str

In [28]:
# now we filter our SCOM and KCB tickers
#for safaricom
scom=df[df["Code"]== "SCOM"].sort_values("Date")
kcb=df[df["Code"]=="KCB"].sort_values("Date")

In [32]:
#lets preview the safaricom data
scom.head()

,Date,Code,Name,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjusted Price
63,2024-01-02,SCOM,Safaricom Plc,12.15,21.15,13.65,13.95,13.75,13.9,-0.15,-1.08%,"176,500.00",-
135,2024-01-03,SCOM,Safaricom Plc,12.15,21.15,13.6,13.9,13.65,13.75,-0.1,-0.73%,"1,666,700.00",-
207,2024-01-04,SCOM,Safaricom Plc,12.15,21.15,13.55,13.8,13.6,13.65,-0.05,-0.37%,"1,000,500.00",-
279,2024-01-05,SCOM,Safaricom Plc,12.15,21.15,13.55,14,13.6,13.6,-,-,"5,622,200.00",-
351,2024-01-08,SCOM,Safaricom Plc,12.15,21.15,13.55,14,13.6,13.6,-,-,"5,622,200.00",-

In [33]:
#lets review the KCB data
kcb.head()

,Date,Code,Name,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjusted Price
14,2024-01-02,KCB,KCB Group Plc,15.75,40,21.8,22,21.95,21.9,0.05,0.23%,"54,700.00",-
86,2024-01-03,KCB,KCB Group Plc,15.75,40,21.95,23.1,22.8,21.95,0.85,3.87%,"172,600.00",-
158,2024-01-04,KCB,KCB Group Plc,15.75,40,22.3,23.1,22.7,22.8,-0.1,-0.44%,"275,400.00",-
230,2024-01-05,KCB,KCB Group Plc,15.75,40,22.45,22.8,22.55,22.7,-0.15,-0.66%,"197,200.00",-
302,2024-01-08,KCB,KCB Group Plc,15.75,40,22.45,22.8,22.55,22.7,-0.15,-0.66%,"197,200.00",-

In [34]:
#we reset the indices
scom.reset_index(drop=True,inplace=True)
kcb.reset_index(drop=True,inplace=True)

In [38]:
# lets check re_indexing
scom.head(2)

,Date,Code,Name,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjusted Price
0,2024-01-02,SCOM,Safaricom Plc,12.15,21.15,13.65,13.95,13.75,13.9,-0.15,-1.08%,"176,500.00",-
1,2024-01-03,SCOM,Safaricom Plc,12.15,21.15,13.6,13.9,13.65,13.75,-0.1,-0.73%,"1,666,700.00",-

In [44]:
#we check re_indexing
kcb.tail(2)

,Date,Code,Name,12m Low,12m High,Day Low,Day High,Day Price,Previous,Change,Change%,Volume,Adjusted Price
247,2024-12-30,KCB,KCB Group Plc,18.5,42.5,39.9,40.5,40,39.95,0.05,0.13%,"959,600.00",-
248,2024-12-31,KCB,KCB Group Plc,18.5,42.8,40,42.5,41.6,40,1.6,4.00%,"136,800.00",-

In [42]:
len(scom)

249

In [43]:
len(kcb)

249